### ISSUE TITLE
isn't this slip132 to descriptor ? 

### ISSUE THREAD

**Issue by fametrano** [RCasatta/electrum2descriptors#1]
see https://github.com/satoshilabs/slips/blob/master/slip-0132.md and the associated test vectors

**Comment by RCasatta** [comment]
yes, it's linked in the readme :)

will add a test to match address derivation

**Comment by RCasatta** [comment]
test added in 549e45c5c86106777007906aa02954bc90971356

**Comment by RCasatta** [comment]
tests running in CI 23c3df5bcc38a5e76752cddb098441ba8c2ab6fa

**Comment by fametrano** [comment]
impressive feedback, fast and effective. kudos. keep up with the good work
