### ISSUE TITLE
also for ExtendedPrivKey

### ISSUE THREAD

**Issue by ulrichard** [RCasatta/electrum2descriptors#5]
Would be cool if the same was also available for private keys.

**Comment by ulrichard** [comment]
I started implementing support for xprv:
https://github.com/ulrichard/electrum2descriptors/tree/feature/xprv
But I ran into a problem. Analogous to the implementation for xpub, am passing 33 bytes to secp256k1::SecretKey::from_slice() while only 32 are required. So I'm not sure where the mismatch comes from.

**Comment by ulrichard** [comment]
Nevermind, I found it in https://github.com/rust-bitcoin/rust-bitcoin/pull/469

**Comment by RCasatta** [comment]
implemented in https://github.com/RCasatta/electrum2descriptors/pull/6
